## You should change each of the following fields
## to customize your blog

title: "My 'Purrsuit' into Data Science--A Clawson Blog"
description: "From my experience from working at BYU Broadcasting as a data analyst, I will be sharing how to translate business and marketing questions into data applications." 
author: Almendra Clawson
author_description: "My name is Almendra Clawson and I love stats as much as I love my cats. I'm majoring in statistics with a data science emphasis and a computer science minor. This is where I'll share my experiences as an undergrad of what I've learned in the data science world." 

url: https://clawmendra.github.io
baseurl: /my-blog ## change this to the name of your blog repository
header_image: /assets/img/darkcatbanner.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github: clawmendra



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




