## You should change each of the following fields
## to customize your blog

title: Answering Business Questions with Data
description: "From my experience from working at BYU Broadcasting as a data analyst, I will be sharing how to 
translate business and marketing questions into data applications." 
author: Almendra Clawson
author_description: "This description of who you are will appear on the 'About' page." 

url: https://clawmendra.github.io
baseurl: /Data Science Applications in Businesses ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github: clawmendra
    twitter: 
    facebook: 
    email: 
    linkedin:
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




